# ~/.config/xmonad/config/clipcat/clipcat-menu.toml  (mod+v)

server_endpoint = "/run/user/1000/clipcat/grpc.sock"
finder = "rofi"
preview_length = 80
grpc_max_message_size = 33554432

[rofi]
line_length = 70
menu_length = 10
menu_prompt = "clipboard"
extra_arguments = ["-theme", "/home/sabir/.config/xmonad/rofi/gruvbox.rasi", "-no-show-icons", "-theme-str", "window {width: 600px; padding: 12px 8px;} element {padding: 7px 10px;}"]
show_source_prefix = false

[dmenu]
line_length = 100
menu_length = 30
menu_prompt = "Clipcat"
extra_arguments = []
show_source_prefix = false

[fuzzel]
line_length = 100
menu_length = 30
menu_prompt = "Clipcat"
extra_arguments = []
show_source_prefix = false

[choose]
line_length = 100
menu_length = 30
menu_prompt = "Clipcat"
extra_arguments = []
show_source_prefix = false

[custom_finder]
program = "fzf"
args = []

[log]
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "INFO"
