#!/usr/bin/env python3
"""turn newtab/quotes.txt into chrome/newtab.css (rotating quotes + facts)."""

from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "quotes.txt"
OUT = HERE.parent / "chrome" / "newtab.css"

QUOTE_SECS, FACT_SECS, FADE_SECS = 9, 22, 0.8

STYLE = {  # per kind: text size, line height, width, label order/colour
    "quote": dict(size="24px", lh="1.45", width="760px", order="1", label="#7c6f64"),
    "fact":  dict(size="16px", lh="1.75", width="620px", order="-1", label="#d79921"),
}


def css_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


items = []
for line in SRC.read_text().splitlines():
    line = line.strip()
    if not line or line.startswith("#"):
        continue
    kind, *rest = [p.strip() for p in line.split("|")]
    if kind == "quote":
        items.append(("quote", rest[0], "—  " + rest[1], QUOTE_SECS))
    elif kind == "fact":
        items.append(("fact", rest[0], "did you know?", FACT_SECS))

total = sum(i[3] for i in items)
pct = lambda t: f"{t * 100 / total:.4f}%"

text_kf, label_kf, fade_kf = [], [], []
t = 0.0
for kind, text, label, secs in items:
    st = STYLE[kind]
    text_kf.append(f"  {pct(t)} {{ content: {css_str(text)}; font-size: {st['size']}; "
                   f"line-height: {st['lh']}; max-width: {st['width']}; }}")
    label_kf.append(f"  {pct(t)} {{ content: {css_str(label)}; order: {st['order']}; color: {st['label']}; }}")
    fade_kf += [f"  {pct(t)} {{ opacity: 0; }}", f"  {pct(t + FADE_SECS)} {{ opacity: 1; }}",
                f"  {pct(t + secs - FADE_SECS)} {{ opacity: 1; }}", f"  {pct(t + secs)} {{ opacity: 0; }}"]
    t += secs

first = items[0]
css = f"""/* generated by newtab/build.py from newtab/quotes.txt -- edit those, not this */

@-moz-document url("about:newtab"), url("about:home") {{
  /* nothing from firefox: no search box, logo, shortcuts or stories */
  body > * {{ display: none !important; }}

  /* the text and its label, centred as one block whatever their length */
  body {{
    display: flex !important;
    flex-direction: column !important;
    align-items: center !important;
    justify-content: center !important;
    gap: 18px;
    min-height: 100vh !important;
    margin: 0 !important;
  }}
  body::before,
  body::after {{
    text-align: center;
    animation-duration: {total:g}s, {total:g}s;
    animation-iteration-count: infinite;
    animation-timing-function: step-end, linear;
  }}
  body::before {{
    content: {css_str(first[1])};
    order: 0;
    max-width: 86vw;
    padding-inline: 24px;
    font-family: "JetBrainsMono Nerd Font", monospace;
    font-weight: 500;
    color: #ebdbb2;
    animation-name: gb-text, gb-fade;
  }}
  body::after {{
    content: {css_str(first[2])};
    font: 12px "Adwaita Sans", "Noto Sans", sans-serif;
    letter-spacing: 1.2px;
    animation-name: gb-label, gb-fade;
  }}

  @keyframes gb-text {{
{chr(10).join(text_kf)}
  }}
  @keyframes gb-label {{
{chr(10).join(label_kf)}
  }}
  @keyframes gb-fade {{
{chr(10).join(fade_kf)}
  }}
}}
"""
OUT.write_text(css)
print(f"{OUT}: {len(items)} items, {total:g}s loop")
