#!/usr/bin/env python3
"""build the new tab page's library.

  build.py          quotes.txt + synced.txt -> quotes.js (the page) and
                    chrome/newtab.css (about:newtab fallback, quotes.txt only)
  build.py --sync   first refresh synced.txt from the quote/fact apis
"""

import json
import sys
import time
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
OWN = HERE / "quotes.txt"      # hand written, never touched by --sync
SYNCED = HERE / "synced.txt"   # pulled from the apis by --sync
JS_OUT = HERE / "quotes.js"
CSS_OUT = HERE.parent / "chrome" / "newtab.css"

QUOTE_SECS, FACT_SECS, FADE_SECS = 9, 22, 0.8
OWN_SHARE = 0.3        # how often the page picks from quotes.txt vs synced.txt
MAX_LEN = 200          # longer api items don't fit the page nicely
FACT_CALLS = 300       # the facts api only hands out one random fact per call

STYLE = {  # per kind: text size, line height, width, label order/colour
    "quote": dict(size="24px", lh="1.45", width="760px", order="1", label="#7c6f64"),
    "fact":  dict(size="16px", lh="1.75", width="620px", order="-1", label="#d79921"),
}


# ---------------------------------------------------------------- sync

def get_json(url):
    req = urllib.request.Request(url, headers={"User-Agent": "gruvbox-newtab/1.0"})
    with urllib.request.urlopen(req, timeout=15) as r:
        return json.load(r)


def clean(s):
    # lowercase like quotes.txt (also fixes dummyjson's "Men'S"), one line, no |
    return " ".join(s.replace("|", "/").replace("`", "'").split()).lower()


def sync():
    lines = ["# generated by build.py --sync -- edit quotes.txt instead", ""]

    quotes = get_json("https://dummyjson.com/quotes?limit=0")["quotes"]
    n_quotes = 0
    for q in quotes:
        text, author = clean(q["quote"]), clean(q["author"])
        if text and len(text) <= MAX_LEN:
            lines.append(f"quote | {text} | {author}")
            n_quotes += 1

    seen, misses = set(), 0
    for _ in range(FACT_CALLS):
        try:
            fact = get_json("https://uselessfacts.jsph.pl/api/v2/facts/random?language=en")
        except Exception as e:
            print(f"facts api: {e}", file=sys.stderr)
            break
        text = clean(fact["text"])
        if fact["id"] in seen or len(text) > MAX_LEN:
            misses += 1
            if misses >= 40:  # the api has run out of new facts
                break
            continue
        seen.add(fact["id"])
        lines.append(f"fact  | {text}")
        time.sleep(0.1)

    SYNCED.write_text("\n".join(lines) + "\n")
    print(f"{SYNCED}: {n_quotes} quotes, {len(seen)} facts")


# ---------------------------------------------------------------- build

def read_items(path):
    items = []
    if not path.exists():
        return items
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        kind, *rest = [p.strip() for p in line.split("|")]
        if kind == "quote":
            items.append(("quote", rest[0], "—  " + rest[1], QUOTE_SECS))
        elif kind == "fact":
            items.append(("fact", rest[0], "did you know?", FACT_SECS))
    return items


def css_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_js(own, synced):
    as_obj = lambda items: [{"kind": k, "text": t, "label": l, "secs": s} for k, t, l, s in items]
    data = {
        "own": as_obj(own),
        "synced": as_obj(synced),
        "ownShare": OWN_SHARE if synced else 1,
        "fade": FADE_SECS,
        "style": STYLE,
    }
    JS_OUT.write_text("// generated by build.py -- edit quotes.txt, not this\n"
                      f"window.GB_LIBRARY = {json.dumps(data, ensure_ascii=False)};\n")
    print(f"{JS_OUT}: {len(own)} own + {len(synced)} synced items")


def write_css(items):
    total = sum(i[3] for i in items)
    pct = lambda t: f"{t * 100 / total:.4f}%"

    text_kf, label_kf, fade_kf = [], [], []
    t = 0.0
    for kind, text, label, secs in items:
        st = STYLE[kind]
        text_kf.append(f"  {pct(t)} {{ content: {css_str(text)}; font-size: {st['size']}; "
                       f"line-height: {st['lh']}; max-width: {st['width']}; }}")
        label_kf.append(f"  {pct(t)} {{ content: {css_str(label)}; order: {st['order']}; color: {st['label']}; }}")
        fade_kf += [f"  {pct(t)} {{ opacity: 0; }}", f"  {pct(t + FADE_SECS)} {{ opacity: 1; }}",
                    f"  {pct(t + secs - FADE_SECS)} {{ opacity: 1; }}", f"  {pct(t + secs)} {{ opacity: 0; }}"]
        t += secs

    first = items[0]
    css = f"""/* generated by newtab/build.py from newtab/quotes.txt -- edit those, not this */
/* fallback only: new tabs normally open newtab/index.html (see autoconfig/mozilla.cfg) */

@-moz-document url("about:newtab"), url("about:home") {{
  /* nothing from firefox: no search box, logo, shortcuts or stories */
  body > * {{ display: none !important; }}

  /* the text and its label, centred as one block whatever their length */
  body {{
    display: flex !important;
    flex-direction: column !important;
    align-items: center !important;
    justify-content: center !important;
    gap: 18px;
    min-height: 100vh !important;
    margin: 0 !important;
  }}
  body::before,
  body::after {{
    text-align: center;
    animation-duration: {total:g}s, {total:g}s;
    animation-iteration-count: infinite;
    animation-timing-function: step-end, linear;
  }}
  body::before {{
    content: {css_str(first[1])};
    order: 0;
    max-width: 86vw;
    padding-inline: 24px;
    font-family: "JetBrainsMono Nerd Font", monospace;
    font-weight: 500;
    color: #ebdbb2;
    animation-name: gb-text, gb-fade;
  }}
  body::after {{
    content: {css_str(first[2])};
    font: 12px "Adwaita Sans", "Noto Sans", sans-serif;
    letter-spacing: 1.2px;
    animation-name: gb-label, gb-fade;
  }}

  @keyframes gb-text {{
{chr(10).join(text_kf)}
  }}
  @keyframes gb-label {{
{chr(10).join(label_kf)}
  }}
  @keyframes gb-fade {{
{chr(10).join(fade_kf)}
  }}
}}
"""
    CSS_OUT.write_text(css)
    print(f"{CSS_OUT}: {len(items)} items, {total:g}s loop")


if "--sync" in sys.argv[1:]:
    sync()
own = read_items(OWN)
write_js(own, read_items(SYNCED))
write_css(own)
