# ~/.config/xmonad/config/alacritty.toml
# imported from ~/.config/alacritty/alacritty.toml

[window]
padding = { x = 14, y = 14 }
dynamic_padding = true
decorations = "None"
opacity = 0.94

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 11.0

[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true

[selection]
save_to_clipboard = true

[colors.primary]
background = "#111618"
foreground = "#d3c6aa"

[colors.cursor]
text = "#111618"
cursor = "#dbbc7f"

[colors.selection]
text = "CellForeground"
background = "#1e2326"

[colors.normal]
black   = "#171c1f"
red     = "#ca6f71"
green   = "#98971a"
yellow  = "#dbbc7f"
blue    = "#7fbbb3"
magenta = "#d699b6"
cyan    = "#83c092"
white   = "#9da9a0"

[colors.bright]
black   = "#859289"
red     = "#ca6f71"
green   = "#b8bb26"
yellow  = "#dbbc7f"
blue    = "#7fbbb3"
magenta = "#d699b6"
cyan    = "#83c092"
white   = "#d3c6aa"
